
# High Scores. First list item is the high score, second list item is the username who scored it.
all_questions = [0,'nobody']		
programming_and_os = [0,'nobody']
theoretical_cs = [0,'nobody']
neuroscience = [0,'nobody']
krr = [0,'nobody']		
logic= [0,'nobody']				
maths_linalg = [0,'nobody']			
mechanics = [0,'nobody']	
presoc_and_plato = [0,'nobody']		
aristotle_and_scholastics = [0,'nobody']		
islamic_world_hist_and_philosophy = [0,'nobody']		
words_tr2 = [0,'nobody']		
words_sp = [0,'nobody']		
words_ru = [0,'nobody']		
words_ar = [0,'nobody']		
words_ja = [0,'nobody']		
words_ch = [0,'nobody']			
words_ch_hanzi = [0,'nobody']

